import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { serialize } from 'next-mdx-remote/serialize';
import {MDXRemote} from 'next-mdx-remote';

import type { NextPage } from 'next'
import Head from 'next/head'

const Project: NextPage = ({ frontMatter: { title, date }, mdxSource }: any) => {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{title}</h1>

      <MDXRemote {...mdxSource} />

    </div>
  )
}

export default Project;

export const getStaticPaths = () => {
  const files = fs.readdirSync(path.join('src', 'posts'));

  const paths = files.map(filename => {
    return {
      params: {
        slug: filename.split('.')[0]
      }
    }
  })

  return {
    paths,
    fallback: false
  }
}

export const getStaticProps = async ({ params: { slug } } : any) => {
  const markdownWithMeta = fs.readFileSync(path.join('src', 'posts', `${slug}.mdx`))

  const { data: frontMatter, content } = matter(markdownWithMeta);
  const mdxSource = await serialize(content);

  return {
    props: {
      frontMatter,
      slug,
      mdxSource
    }
  }

}
