import fs from 'fs';
import * as path from 'path';
import type { NextPage } from 'next'
import matter from 'gray-matter';
import Head from 'next/head';
import Link from 'next/link';

const Projects: NextPage = ({ posts } : any) => {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Projects</h1>

      {posts.map((post: any, index: number) => (
        <Link href={`/projects/${post.slug}`} key={index}>{post.frontMatter.title}</Link>
      ))}

    </div>
  )
}

export default Projects

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('src', 'posts', 'projects'))

  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('src', 'posts', 'projects', filename)) as any;
    const { data: frontMatter } = matter(markdownWithMeta);

    return {
      frontMatter,
      slug: filename.split('.')[0]
    }

  })

  return {
    props: {
      posts
    }
  }
}
