import fs from 'fs';
import * as path from 'path';
import type { NextPage } from 'next'
import matter from 'gray-matter';
import Head from 'next/head';
import Link from 'next/link';

import styles from '../../styles/Projects.module.css';

import Cover from '../../components/cover';

const Projects: NextPage = ({ posts } : any) => {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.projects}>
        {posts.map(({ frontMatter, slug } : any, index: number) => {
          return (
            <Link href={`/projects/${slug}`} key={index}>
              <a draggable={false} className={styles.col}>
                <Cover
                  covered={true}
                  fixedHeight={true}
                  name={frontMatter.title}
                  logoWidth={frontMatter.coverLogoWidth}
                  logoHeight={frontMatter.coverLogoHeight}
                  screenImgUrl={frontMatter.coverScreenshotUrl}
                  logoImgUrl={frontMatter.coverLogoUrl}
                  bgColor={frontMatter.coverBackgroundColor}
                />
              </a>
            </Link>
          )
        })}
      </div>

    </div>
  )
}

export default Projects

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('src', 'posts', 'projects'))

  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('src', 'posts', 'projects', filename)) as any;
    const { data: frontMatter } = matter(markdownWithMeta);

    return {
      frontMatter,
      slug: filename.split('.')[0]
    }

  })

  return {
    props: {
      posts
    }
  }
}
